platform :ios,        '8.0'
source 'https://github.com/CocoaPods/Specs.git'

# inhibit_all_warnings!

target 'Sample' do
pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'RCTText',
  'RCTImage',
  'RCTNetwork',
  'RCTWebSocket',
]
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'SimulatorRemoteNotifications', '~> 0.0.3'
end
